server:
  port: 8092
  servlet:
    context-path: /pm2/flow-manager
spring:
  datasource:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:sqlserver://192.168.3.253:1433;database=sdb_flow_manager;integratedSecurity=false
#      url: jdbc:mysql://127.0.0.1:3306/flow_manager?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=true
      username: song
      password: 85516128
#      db-type: mysql
  thymeleaf:
    cache: false
    prefix: classpath:templates/
    suffix: .html
    mode: HTML
  redis:
    host: 192.168.3.253
    database: 0
    port: 6379
mybatis-plus:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.song.entity
flow-manager:
  token-verify: 0
  client-url: http://192.168.2.254:8089/pm2
  get-person-url: http://192.168.2.254:8089/pm2/api/getSystemPerson