server:
  port: 8092
  servlet:
    context-path: /pm2/flow-manager
spring:
  datasource:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      password: 85516128
      username: song
      url: jdbc:sqlserver://192.168.3.253:1433;database=sdb_flow_manager;integratedSecurity=false
      db-type: sqlserver
  thymeleaf:
    cache: false
    prefix: classpath:templates/
    suffix: .html
    mode: HTML
mybatis-plus:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.song.entity